import { Inter } from 'next/font/google'
import './globals.css'
import Providers from '@/app/providers'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-2-6xl container mx-auto px-4">
          <Providers>
            <Header />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  )
}
